# Generated by Django 4.1.5 on 2023-04-09 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(default=None, help_text='Производитель', on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Выберите продукты', related_name='shops', through='shops.ShopProduct', to='shops.product', verbose_name='Продукты'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(help_text='Выберите подкатегорию', related_name='Подкатегории', to='shops.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='favoriteshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_shops', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='favoriteshop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to='shops.product'),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='shopproduct',
            constraint=models.UniqueConstraint(fields=('shop', 'product'), name='unique_shop_product'),
        ),
        migrations.AddConstraint(
            model_name='shopmessenger',
            constraint=models.UniqueConstraint(fields=('shop', 'messenger'), name='unique_shop_messenger'),
        ),
        migrations.AddConstraint(
            model_name='favoriteshop',
            constraint=models.UniqueConstraint(fields=('user', 'shop'), name='unique_favorite_shop'),
        ),
        migrations.AddConstraint(
            model_name='favoriteproduct',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_favorite_product'),
        ),
    ]
