# Generated by Django 4.1.5 on 2023-03-06 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Продукт магазина',
                'verbose_name_plural': 'Продукты магазина',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'ordering': ('user',), 'verbose_name': 'Избранный продукт', 'verbose_name_plural': 'Избранные продукты'},
        ),
        migrations.AlterModelOptions(
            name='favoriteshop',
            options={'ordering': ('user',), 'verbose_name': 'Избранный магазин', 'verbose_name_plural': 'Избранные магазины'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('name',), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='adress',
            field=models.CharField(default=None, help_text='Введите адрес магазина', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='shop',
            name='contacts',
            field=models.CharField(default=None, max_length=200, verbose_name='Контактная информация'),
        ),
        migrations.AddField(
            model_name='shop',
            name='coordinates',
            field=models.CharField(default=None, help_text='Введите координаты магазина', max_length=200, verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='shop',
            name='delivery',
            field=models.CharField(default=None, max_length=200, verbose_name='Доставка'),
        ),
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default=None, help_text='Введите описание магазина', verbose_name='Описание магазина'),
        ),
        migrations.AddField(
            model_name='shop',
            name='history',
            field=models.TextField(default=None, help_text='Введите историю создания магазина', verbose_name='История создания магазина'),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, upload_to='shops/images/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='shop',
            name='mainstream',
            field=models.CharField(default=None, help_text='Введите осносное направление магазина', max_length=200, verbose_name='Основное направление'),
        ),
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default=None, help_text='Введите название продукта', max_length=200, verbose_name='Название продута'),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(default=None, help_text='Производитель', on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='shop',
            name='photo',
            field=models.ImageField(blank=True, upload_to='shops/images/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='shop',
            name='presented',
            field=models.CharField(default=None, help_text='Введите где представлен продукт', max_length=200, verbose_name='Где представлен продукт'),
        ),
        migrations.AddField(
            model_name='shop',
            name='sertificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='sertificate_photo',
            field=models.ImageField(blank=True, upload_to='shops/images/', verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Введите название категории', max_length=200, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите картинку', upload_to='shops/images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Введите слаг', max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to='shops.product'),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_shops', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='favoriteshop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Введите описание продукта', verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Введите название продукта', max_length=200, verbose_name='Название продута'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите картинку', upload_to='shops/images/', verbose_name='Картинка'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(help_text='Категория', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='shops.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text='Введите название подкатегории', max_length=200, verbose_name='Название подкатегории'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(help_text='Введите слаг', max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddConstraint(
            model_name='favoriteproduct',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_favorite_product'),
        ),
        migrations.AddConstraint(
            model_name='favoriteshop',
            constraint=models.UniqueConstraint(fields=('user', 'shop'), name='unique_favorite_shop'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='shops.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='shops.shop', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='shop',
            name='product',
            field=models.ManyToManyField(blank=True, help_text='Выберите продукты', related_name='shops', through='shops.ShopProduct', to='shops.product', verbose_name='Продукты'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(help_text='Выберите подкатегорию', related_name='Подкатегории', to='shops.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddConstraint(
            model_name='shopproduct',
            constraint=models.UniqueConstraint(fields=('shop', 'product'), name='unique_shop_product'),
        ),
    ]
