# Generated by Django 4.1.5 on 2023-03-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shopproduct_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='product',
            new_name='products',
        ),
        migrations.AddField(
            model_name='shop',
            name='categorys',
            field=models.ManyToManyField(help_text='Выберите категории', related_name='магазины', to='shops.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='shop',
            name='subcategorys',
            field=models.ManyToManyField(help_text='Выберите подкатегории', related_name='магазины', to='shops.subcategory', verbose_name='Подкатегории'),
        ),
    ]
