# Generated by Django 4.1.5 on 2023-03-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_rename_product_shop_products_shop_categorys_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name': 'Субкатегория', 'verbose_name_plural': 'Субкатегории'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(default=None, help_text='Введите название магазина', max_length=200, verbose_name='Название магазина'),
        ),
    ]
