# Generated by Django 4.1.5 on 2023-03-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_subcategory_options_alter_shop_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='adress',
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default=None, help_text='Введите город', max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='shop',
            name='house',
            field=models.CharField(default=None, help_text='Введите номер дома', max_length=10, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='shop',
            name='region',
            field=models.CharField(default=None, help_text='Введите регион', max_length=50, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='shop',
            name='street',
            field=models.CharField(default=None, help_text='Введите название улицы', max_length=50, verbose_name='Улица'),
        ),
    ]
